name: amjaadiot_task
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.3.1
  easy_localization: ^3.0.0
  dio: ^4.0.4
  provider: ^6.0.2
  bottom_navy_bar: ^6.0.0
  pull_to_refresh: ^2.0.0
  flutter_rating_bar: ^4.0.0
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  flutter_switch: ^0.3.2
  google_maps_flutter: ^2.1.2
  permission_handler: ^9.2.0
  material_floating_search_bar: ^0.3.7
  geolocator: ^8.1.1
  uuid: ^3.0.5
  google_maps_place_picker_mb: ^2.0.0-mb.15
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
 


flutter:
  uses-material-design: true
  assets:
    - lib/public/translations/

